### ISSUE TITLE
Dynamic linking error when following install & usage

### ISSUE THREAD

**Issue by jlsjonas** [k-egor-smirnov/node-tg-native#6]
node v. 8.4.0

```node_modules/ffi/lib/dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err)
    ^

Error: Dynamic Linking Error: dlopen(project/node_modules/node-tg-native/bin/libtdjson.dylib, 2): image not found
    at new DynamicLibrary (project/node_modules/ffi/lib/dynamic_library.js:74:11)
    at Object.Library (project/node_modules/ffi/lib/library.js:45:12)
    at Object.<anonymous> (project/node_modules/node-tg-native/lib/TD.js:15:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)```

From what I see it tries to find `bin/libtdjson.dylib`, which doesn't exist

**Comment by alt3rmann** [comment]
It's bug only in mac os. 
dylib - is a mac os lib format. In linux libs have ext .so

**Comment by jlsjonas** [comment]
Thanks for the extra info @alt3rmann, would be a PITA to develop without macOs support though 😅

**Comment by k-egor-smirnov** [comment]
I doesn't have a OSX and it's be good if anybody send pull request
